name: 'Notify'
description: 'Notify developers of changes to a specific path via submitting a Pull Request'
author: "Poolitzer"
inputs:
  notify-message:
    description: "Message to comment when a user opens a PR"
    default: "Heyho, this is a little reminder that someone changed the file(s) here :)"
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
